"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['instead-manager-tk.pyw']
DATA_FILES = ['instead-manager-tk.pyw']
OPTIONS = {'argv_emulation': True, 'packages': ['packages'], 'resources': ['resources', 'skeleton'],
           'iconfile': 'resources/images/logo.icns'}

setup(
    name='INSTEAD Manager',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
